
POST localhost:9003/p2p/chat
Content-Type: application/json

{
  "fromUserId" : "101",
  "toUserId" : "100",
  "msg" : "你好"
}

###

POST localhost:9003/login/logout/101
Content-Type: application/json

###